name = "agendeibr"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://wldifxcwobyeqbvwatgr.supabase.co/rest/v1/"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsZGlmeGN3b2J5ZXFidndhdGdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgyNjczMjIsImV4cCI6MjEwMzg0MzMyMn0.RG6CnZP9TRAdclSXp0FeixhbakR3Dq-vittH427X9ZM"
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_sgxmc6_4FBQvXmpEx1tASQ_0sojTegq"